name: framework spellcheck
on:
  push:
    branches:
    - the-one
    paths:
    - 'framework/language/en.yml'
    - '.github/workflows/framework.spellcheck.yml'
    - '.dictionary.txt'
  pull_request:
    branches:
    - the-one
    paths:
    - 'framework/language/en.yml'
    - '.github/workflows/framework.spellcheck.yml'
    - '.dictionary.txt'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            framework/package-lock.json
            package-lock.json
      - run: cd framework && npm ci
      - run: cd framework && npm run spellcheck
