name: conflibot
on:
  pull_request:
    branches:
      - the-one

jobs:
  conflibot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Warn potential conflicts
        uses: idrinth/conflibot@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            **/package-lock.json
